### ISSUE TITLE
Infinite addition of Wire in case of incorrect roof construction

### ISSUE THREAD

**Issue by kaiwas** [ebrahimraeyat/PitchedRoof#3]
If we made a sketch incorrectly (for example counterclockwise or built a rectangle), "Wire" starts to appear in the document after each command.
Demonstration on video.

https://github.com/user-attachments/assets/ba481dc0-d003-4e12-9f58-a25016227b66

**Comment by paullee0** [comment]
Is it the BIM  ArchRoof tool ?

**Comment by kaiwas** [comment]
> Is it the BIM ArchRoof tool ?

No, this tool generates a surface.
But the surface can be extruded and wrapped with ArchRoof.

**Comment by kaiwas** [comment]
> Is it the BIM ArchRoof tool ?

The most important thing is that this tool is adaptive. It rebuilds the shape if the shape changes. For example, if you replace a rectangle with a more complex shape.

https://github.com/ebrahimraeyat/PitchedRoof

**Comment by paullee0** [comment]
I see, I remember that external add-on, very impressive, would the additional wires created by the add-on ?

**Comment by kaiwas** [comment]
> I see, I remember that external add-on, very impressive, would the additional wires created by the add-on ?

I didn't understand the question (maybe there were translation difficulties)

**Comment by paullee0** [comment]
I watch your video again.  It seems you are using external add-on Roof tool, not yet wrapped under the stock ArchRoof yet, and the additional wires appear, correct?

If positive, this is a bug report to the external Roof tool.

That's my guess.

**Comment by kaiwas** [comment]
> I watch your video again. It seems you are using external add-on Roof tool, not yet wrapped under the stock ArchRoof yet, and the additional wires appear, correct?
> 
> If positive, this is a bug report to the external Roof tool.
> 
> That's my guess.

Wires appear when the tool isn't working correctly (previously, this happened if a closed figure was drawn counterclockwise).
This appears to be a defect in the add-on. If an error occurs, the add-on doesn't disable itself and generates empty wires.

It's a shame that this add-on has been abandoned by its developer.

https://github.com/user-attachments/assets/a7df9048-4701-497c-8258-d82d97018e16

**Comment by paullee0** [comment]
I see, not used that add-on.

What is the strength and difference with FC ArchRoof?

Maybe do a feature request to merge that if someone has a time and interest?

**Comment by kaiwas** [comment]
> What is the strength and difference with FC ArchRoof?

The main advantage of this component is that it creates correct roof slopes for almost any roof profile configuration.

ArchRoof also has a lot of settings that are difficult to configure (unwieldy lists).

Video demonstration.

https://github.com/user-attachments/assets/25a716c1-4080-4dce-8a8d-d20f5d358662

https://github.com/user-attachments/assets/523056b3-7c89-4ee9-94e1-b1ce9e76a8a4

> Maybe do a feature request to merge that if someone has a time and interest?

Someday I'll get to the roof in the main branch. But there will be a lot of requests ))) So I'm in no rush.

**Comment by markkomartin** [comment]
Thanks to @ErtugrulEge help I managed to install PitchedRoof wb on Windows.
In my opinion, the problems reported in this ticket appear to have been resolved.

https://github.com/user-attachments/assets/de65c8b8-1868-47da-8fe3-80a36e7e4b5a

**Comment by kaiwas** [comment]
> In my opinion, the problems reported in this ticket appear to have been resolved.

Yes. The problem is partially solved and no longer depends on the sketch's construction direction.  (I hired a third-party programmer to solve this problem.)
But the problem still exists.
Try plotting a straight line (not a closed one) in the sketch.
It seems that if an error occurs, the command runs indefinitely.

**Comment by ebrahimraeyat** [comment]
I will look into this error.

**Comment by ebrahimraeyat** [comment]
in my freecad if the roof get error, refresh or press F5, did not generate the additional wire. do you use modified version of pitchedRoof?

OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24291 (Git)
Build type: Release
Branch: releases/FreeCAD-0-19
Hash: 7b5e18a0759de778b74d3a5c17eba9cb815035ac
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US)

**Comment by kaiwas** [comment]
> do you use modified version

No. I'm using the unmodified version from GitHub.

The problem is indeed harder to reproduce. But I still encounter it.

If I have a stable example, I'll definitely let you know. For now, let's assume the problem is mostly gone.

Thnx!

**Comment by ErtugrulEge** [comment]
Firstly, this is a very powerful and easy to use roof tool. Thanks to the developer. 

I downloaded from github

1.Create roof
2.Part extrude
3.Delete extrude
4.Select  some sketch edges and press ptiched_roof_angle


https://github.com/user-attachments/assets/f7a7fd88-e259-486c-8491-f9e8923ebb6b

```
12:27:15  pyException: Traceback (most recent call last):
  File "C:\Users\user\Desktop\FreeCAD_weekly-2025.12.31-Windows-x86_64-py311\Mod\PitchedRoof\roof3d.py", line 84, in execute
    projection_face_points, wire_edges = extrude_pieces.create_3D_roof(base_obj, obj.angle, [], obj.angles)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\FreeCAD_weekly-2025.12.31-Windows-x86_64-py311\Mod\PitchedRoof\extrude_pieces.py", line 104, in create_3D_roof
    x, y = mirror_point_corresponding_to_edge_in_xy(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\FreeCAD_weekly-2025.12.31-Windows-x86_64-py311\Mod\PitchedRoof\pitched_roof_funcs.py", line 32, in mirror_point_corresponding_to_edge_in_xy
    m = (y3 - y2) / (x3 - x2)
        ~~~~~~~~~~^~~~~~~~~~~
<class 'ZeroDivisionError'>: float division by zero
12:27:15  Roof: float division by zero
12:27:17  pyException: Traceback (most recent call last):
  File "C:\Users\user\Desktop\FreeCAD_weekly-2025.12.31-Windows-x86_64-py311\Mod\PitchedRoof\roof3d.py", line 84, in execute
    projection_face_points, wire_edges = extrude_pieces.create_3D_roof(base_obj, obj.angle, [], obj.angles)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\FreeCAD_weekly-2025.12.31-Windows-x86_64-py311\Mod\PitchedRoof\extrude_pieces.py", line 104, in create_3D_roof
    x, y = mirror_point_corresponding_to_edge_in_xy(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\FreeCAD_weekly-2025.12.31-Windows-x86_64-py311\Mod\PitchedRoof\pitched_roof_funcs.py", line 32, in mirror_point_corresponding_to_edge_in_xy
    m = (y3 - y2) / (x3 - x2)
        ~~~~~~~~~~^~~~~~~~~~~
<class 'ZeroDivisionError'>: float division by zero
12:27:17  Roof: float division by zero
12:27:17  pyException: Traceback (most recent call last):
  File "C:\Users\user\Desktop\FreeCAD_weekly-2025.12.31-Windows-x86_64-py311\Mod\PitchedRoof\roof3d.py", line 84, in execute
    projection_face_points, wire_edges = extrude_pieces.create_3D_roof(base_obj, obj.angle, [], obj.angles)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\FreeCAD_weekly-2025.12.31-Windows-x86_64-py311\Mod\PitchedRoof\extrude_pieces.py", line 104, in create_3D_roof
    x, y = mirror_point_corresponding_to_edge_in_xy(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\FreeCAD_weekly-2025.12.31-Windows-x86_64-py311\Mod\PitchedRoof\pitched_roof_funcs.py", line 32, in mirror_point_corresponding_to_edge_in_xy
    m = (y3 - y2) / (x3 - x2)
        ~~~~~~~~~~^~~~~~~~~~~
<class 'ZeroDivisionError'>: float division by zero
12:27:17  Roof: float division by zero
12:27:18  pyException: Traceback (most recent call last):
  File "C:\Users\user\Desktop\FreeCAD_weekly-2025.12.31-Windows-x86_64-py311\Mod\PitchedRoof\roof3d.py", line 84, in execute
    projection_face_points, wire_edges = extrude_pieces.create_3D_roof(base_obj, obj.angle, [], obj.angles)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\FreeCAD_weekly-2025.12.31-Windows-x86_64-py311\Mod\PitchedRoof\extrude_pieces.py", line 104, in create_3D_roof
    x, y = mirror_point_corresponding_to_edge_in_xy(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\FreeCAD_weekly-2025.12.31-Windows-x86_64-py311\Mod\PitchedRoof\pitched_roof_funcs.py", line 32, in mirror_point_corresponding_to_edge_in_xy
    m = (y3 - y2) / (x3 - x2)
        ~~~~~~~~~~^~~~~~~~~~~
<class 'ZeroDivisionError'>: float division by zero
12:27:18  Roof: float division by zero
12:27:18  pyException: Traceback (most recent call last):
  File "C:\Users\user\Desktop\FreeCAD_weekly-2025.12.31-Windows-x86_64-py311\Mod\PitchedRoof\roof3d.py", line 84, in execute
    projection_face_points, wire_edges = extrude_pieces.create_3D_roof(base_obj, obj.angle, [], obj.angles)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\FreeCAD_weekly-2025.12.31-Windows-x86_64-py311\Mod\PitchedRoof\extrude_pieces.py", line 104, in create_3D_roof
    x, y = mirror_point_corresponding_to_edge_in_xy(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\FreeCAD_weekly-2025.12.31-Windows-x86_64-py311\Mod\PitchedRoof\pitched_roof_funcs.py", line 32, in mirror_point_corresponding_to_edge_in_xy
    m = (y3 - y2) / (x3 - x2)
        ~~~~~~~~~~^~~~~~~~~~~
<class 'ZeroDivisionError'>: float division by zero
12:27:18  Roof: float division by zero
12:27:18  pyException: Traceback (most recent call last):
  File "C:\Users\user\Desktop\FreeCAD_weekly-2025.12.31-Windows-x86_64-py311\Mod\PitchedRoof\roof3d.py", line 84, in execute
    projection_face_points, wire_edges = extrude_pieces.create_3D_roof(base_obj, obj.angle, [], obj.angles)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\FreeCAD_weekly-2025.12.31-Windows-x86_64-py311\Mod\PitchedRoof\extrude_pieces.py", line 104, in create_3D_roof
    x, y = mirror_point_corresponding_to_edge_in_xy(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\FreeCAD_weekly-2025.12.31-Windows-x86_64-py311\Mod\PitchedRoof\pitched_roof_funcs.py", line 32, in mirror_point_corresponding_to_edge_in_xy
    m = (y3 - y2) / (x3 - x2)
        ~~~~~~~~~~^~~~~~~~~~~
<class 'ZeroDivisionError'>: float division by zero
12:27:18  Roof: float division by zero
12:27:18  pyException: Traceback (most recent call last):
  File "C:\Users\user\Desktop\FreeCAD_weekly-2025.12.31-Windows-x86_64-py311\Mod\PitchedRoof\roof3d.py", line 84, in execute
    projection_face_points, wire_edges = extrude_pieces.create_3D_roof(base_obj, obj.angle, [], obj.angles)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\FreeCAD_weekly-2025.12.31-Windows-x86_64-py311\Mod\PitchedRoof\extrude_pieces.py", line 104, in create_3D_roof
    x, y = mirror_point_corresponding_to_edge_in_xy(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\FreeCAD_weekly-2025.12.31-Windows-x86_64-py311\Mod\PitchedRoof\pitched_roof_funcs.py", line 32, in mirror_point_corresponding_to_edge_in_xy
    m = (y3 - y2) / (x3 - x2)
        ~~~~~~~~~~^~~~~~~~~~~
<class 'ZeroDivisionError'>: float division by zero
12:27:18  Roof: float division by zero
```
